### ISSUE TITLE
I updated data but this still happening...

### ISSUE THREAD

**Issue by NiteSpicy** [AthallahDzaki/SAMPMobile#4]
**Loading peds.ide..
SIGSEGV | Fault address: 0x45043358
libGTASA base address: 0x4000000
register states:
r0: 0x51562D4, r1: 0x92DFFB30, r2: 0x93707F00, r3: 0x45043359
r4: 0x51562d4, r5: 0x4890318, r6: 0x92dffb84, r7: 0x92dffae8
r8: 0x92dffb1c, r9: 0xb5f58008, sl: 0x92dffb54, fp: 0x92dffb30
ip: 0x95592400, sp: 0x92dffab8, lr: 0x44055b9, pc: 0x434ac8d
backtrace (libGTASA | libSAMP):
1: 0x434AC8D (0x34AC8D | 0xFF34AC8D)
2: 0x44055B9 (0x4055B9 | 0xFF4055B9)**

**Comment by NikaGeo** [comment]
Me too😭

**Comment by NiteSpicy** [comment]
Fixed...

**Comment by Henrique1748** [comment]
what was the problem? could you tell me how to fix the problem?
