### ISSUE TITLE
Crashed while loading 

### ISSUE THREAD

**Issue by Henrique1748** [AthallahDzaki/SAMPMobile#6]
SIGSEGV | Fault address: 0x1D5A
libGTASA base address: 0x4000000
register states:
r0: 0x4, r1: 0xA0600918, r2: 0xA0600998, r3: 0x0
r4: 0x0, r5: 0x48b6c60, r6: 0x200, r7: 0xa0600c88
r8: 0x48b6c60, r9: 0x0, sl: 0x49e75b8, fp: 0x1ff
ip: 0xa0600430, sp: 0xa0600918, lr: 0xa416bcc5, pc: 0x0
backtrace (libGTASA | libSAMP):
1: 0x0 (0xFC000000 | 0xFB000000)
2: 0xA416BCC5 (0xA016BCC5 | 0x9F16BCC5)

any tips on how to fix it?

**Comment by srkibi** [comment]
I'm solving this error now when I succeed I show you how to fix

**Comment by AthallahDzaki** [comment]
Use my data

**Comment by Henrique1748** [comment]
> Use my data

I'm using your data. Do you have any specific apk to inject the lib?

**Comment by Henrique1748** [comment]
up

**Comment by AthallahDzaki** [comment]
APK easy tool

**Comment by Henrique1748** [comment]
> APK easy tool

Im using the APK easy tool. I am also using the files that you have made available, but, I always get the same error:

> GTA pools initializing..
SIGSEGV | Fault address: 0x4
libGTASA base address: 0x4000000
register states:
r0: 0x0, r1: 0x48B6C60, r2: 0x200, r3: 0x450000
r4: 0x0, r5: 0x48b6c60, r6: 0x200, r7: 0xa06ffc88
r8: 0x48b6c60, r9: 0x0, sl: 0x49e75b8, fp: 0x1ff
ip: 0xa06ffce2, sp: 0xa06ffcd0, lr: 0x43961dd, pc: 0x423b6d8
backtrace (libGTASA | libSAMP):
1: 0x423B6D8 (0x23B6D8 | 0xFF23B6D8)
2: 0x43961DD (0x3961DD | 0xFF3961DD)

Do you think it could be the version of gta? would you recommend me a version?

**Comment by AthallahDzaki** [comment]
Use v1.08

**Comment by rogeriomascari** [comment]
@Henrique1748 I have the same problem here, did you find a solution?
